export const LANGUAGES = [
  { code: 'EN', label: 'English' },
  { code: 'FR', label: 'French' },
  { code: 'ES', label: 'Spanish' },
  { code: 'DE', label: 'German' },
  { code: 'IT', label: 'Italian' },
  { code: 'PT', label: 'Portuguese' },
  { code: 'ZH', label: 'Chinese (Simplified)' },
  { code: 'ZT', label: 'Chinese (Traditional)' },
  { code: 'JA', label: 'Japanese' },
  { code: 'KO', label: 'Korean' },
  { code: 'AR', label: 'Arabic' },
  { code: 'HI', label: 'Hindi' },
  { code: 'RU', label: 'Russian' },
  { code: 'TH', label: 'Thai' },
  { code: 'VI', label: 'Vietnamese' },
  { code: 'ID', label: 'Indonesian' },
  { code: 'MS', label: 'Malay' },
  { code: 'NL', label: 'Dutch' },
  { code: 'PL', label: 'Polish' },
  { code: 'SV', label: 'Swedish' },
  { code: 'TR', label: 'Turkish' },
  { code: 'UK', label: 'Ukrainian' },
  { code: 'CS', label: 'Czech' },
  { code: 'RO', label: 'Romanian' },
  { code: 'HU', label: 'Hungarian' },
  { code: 'EL', label: 'Greek' },
  { code: 'HE', label: 'Hebrew' },
  { code: 'DA', label: 'Danish' },
  { code: 'FI', label: 'Finnish' },
  { code: 'NO', label: 'Norwegian' },
  { code: 'TL', label: 'Filipino' },
  { code: 'FA', label: 'Persian' },
  { code: 'BN', label: 'Bengali' },
  { code: 'HR', label: 'Croatian' },
  { code: 'SK', label: 'Slovak' },
  { code: 'BG', label: 'Bulgarian' },
  { code: 'SR', label: 'Serbian' },
]
