export const LANGUAGES = [
  { code: 'en', label: 'English', flag: 'EN' },
  { code: 'es', label: 'Spanish', flag: 'ES' },
  { code: 'fr', label: 'French', flag: 'FR' },
  { code: 'de', label: 'German', flag: 'DE' },
  { code: 'it', label: 'Italian', flag: 'IT' },
  { code: 'pt', label: 'Portuguese', flag: 'PT' },
  { code: 'zh', label: 'Chinese (Simplified)', flag: 'ZH' },
  { code: 'ja', label: 'Japanese', flag: 'JA' },
  { code: 'ko', label: 'Korean', flag: 'KO' },
  { code: 'ar', label: 'Arabic', flag: 'AR' },
  { code: 'hi', label: 'Hindi', flag: 'HI' },
  { code: 'ru', label: 'Russian', flag: 'RU' },
  { code: 'th', label: 'Thai', flag: 'TH' },
  { code: 'vi', label: 'Vietnamese', flag: 'VI' },
  { code: 'id', label: 'Indonesian', flag: 'ID' },
  { code: 'ms', label: 'Malay', flag: 'MS' },
  { code: 'nl', label: 'Dutch', flag: 'NL' },
  { code: 'pl', label: 'Polish', flag: 'PL' },
  { code: 'sv', label: 'Swedish', flag: 'SV' },
  { code: 'tr', label: 'Turkish', flag: 'TR' },
  { code: 'uk', label: 'Ukrainian', flag: 'UK' },
  { code: 'cs', label: 'Czech', flag: 'CS' },
  { code: 'ro', label: 'Romanian', flag: 'RO' },
  { code: 'hu', label: 'Hungarian', flag: 'HU' },
  { code: 'el', label: 'Greek', flag: 'EL' },
  { code: 'he', label: 'Hebrew', flag: 'HE' },
  { code: 'da', label: 'Danish', flag: 'DA' },
  { code: 'fi', label: 'Finnish', flag: 'FI' },
  { code: 'no', label: 'Norwegian', flag: 'NO' },
  { code: 'tl', label: 'Filipino', flag: 'TL' },
]
